Add the Glance deployment document
kungze/documents pull request #5
Opened 2022-06-17 00:46 UTC by caotingv

2022-06-20 09:47 UTC, jeffyjf commented
对于 openstack-dep 的改动，文档中相应的也要改一下。

2022-06-27 06:08 UTC, jeffyjf requested changes

2022-06-27 06:08 UTC, jeffyjf commented on content/kolla-helm/dependency/index.md
> +默认情况下，openstack-dep 会部署 ceph 相关的 configmap，若环境中未使用 ceph ， 可通过以下命令来跳过这一步骤。
这一段可以尝试加更过的解释，这个 configmap 有什么作用，怎么创建的？ceph.enabled 什么情况下应该设置为 False，什么情况下应该设置为 True。

2022-07-27 00:07 UTC, jeffyjf commented
![1658880369005_09A3524D-7683-4c10-9250-868F251F39E8](https://user-images.githubusercontent.com/12678614/181132938-b448e42b-32f7-42e5-90a7-203937ca3da5.png)
 最后一个 commit 是怎么出现的？

2022-07-27 00:49 UTC, caotingv commented
> ![1658880369005_09A3524D-7683-4c10-9250-868F251F39E8](https://user-images.githubusercontent.com/12678614/181132938-b448e42b-32f7-42e5-90a7-203937ca3da5.png) 最后一个 commit 是怎么出现的？

已解决，原因是之前为了看效果合并了分支。

2022-07-27 03:05 UTC, jeffyjf approved these changes

2022-07-27 03:05 UTC, merged